[package]
name = "risc0-circuits"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.19" }

[package.metadata.risc0]
methods = ["guest"]
