name: wsctl release

on:
  push:
    tags:
      - "v*"

jobs:
  release_job:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: wsctl-linux-amd64
          - os: windows-latest
            artifact_name: wsctl-windows-amd64.exe
          - os: macos-latest
            artifact_name: wsctl-darwin-amd64
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: make wsctl
        run: |
          set CGO_ENABLED=1
          set GOARCH=amd64
          go build -o ./${{ matrix.artifact_name }} -v ./cmd/wsctl

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.artifact_name }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
